---
- name: Install and configure Open Telemetry collector
  hosts: agents
  become: true
  tasks:
    - name: "Include opentelemetry_collector"
      include_role:
        name: "opentelemetry_collector"

- name: Install and configure Open Telemetry gateway collector
  hosts: gateways
  become: true
  tasks:
    - name: "Include opentelemetry_collector"
      include_role:
        name: "opentelemetry_collector"
      vars:
        collector_config_tpl: "otel-config-gw.yaml.j2"
